name: Scheduled Node.js Job

on:
  schedule:
    - cron: '30 1 * * *' # Runs at 7:00 AM UTC every day
    - cron: '30 12 * * *' # Runs at 6:00 PM UTC every day
    - cron: '45 3 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install

      - name: Run the script for 7 AM task
        if: github.event.schedule == '30 1 * * *'
        run: node -e 'require("./app").main(0,10)'

      - name: Run the script for 6 PM task
        if: github.event.schedule == '45 3 * * *'
        run: node -e 'require("./app").main(10,20)'

      - name: Run the script for 6 PM task
        if: github.event.schedule == '30 12 * * *'
        run: node -e 'require("./app").main(10,20)'
        
   
