name: Scheduled Node.js Job

on:
  schedule:
    - cron: '16 6 * * *' # Runs at 6:00 AM UTC every day
    - cron: '20 6 * * *' # Runs at 7:00 PM UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install

      - name: Run the script for 6 AM task
        if: github.event.schedule == '16 6 * * *'
        run: node -e 'require("./app").main(0,10)'

      - name: Run the script for 7 PM task
        if: github.event.schedule == '20 6 * * *'
        run: node -e 'require("./app").main(10,20)'
